### ISSUE TITLE
Add linter

### ISSUE THREAD

**Issue by Danwhy** [dwyl/protect-main-branch#3]
We should look at adding a linter to this project if we do any more work on it.

Elixir linter options:
* [Credo](https://github.com/rrrene/credo)
* [Dogma](https://github.com/lpil/dogma)

**Comment by ZooeyMiller** [comment]
I've only used Credo in the past but it worked pretty well for me. It seems that Dogma is more for enforcing a style guide, which if we were adding a linter, would probably be our intention (especially if in combination with a pre-commit/CI), but this experience can be mimicked by the `--strict` flag in Credo. 

If no one has any other strong opinions I'll happily add a PR to add Credo in and set up a pre-commit RE #4

**Comment by Danwhy** [comment]
:+1: Credo works for me, I've used and liked it before too
