### ISSUE TITLE
Why?

### ISSUE THREAD

**Issue by nelsonic** [dwyl/protect-main-branch#6]
# Todo 
+ [x] Add brief intro as to _Why_ this repo/script is _useful_.

**Comment by iteles** [comment]
Reference: https://github.com/dwyl/hq/issues/403

**Comment by nelsonic** [comment]
@iteles thank you for linking to the original requirement. 
Without that link, someone who was unfamiliar with the HQ issue would only _understand_ the usecase for this code by reading the commit history and clicking the linked issues ... which is a _lot_ better than not having any linked issues in commit messages ... but it would be best if the docs were up-to-date.

**Comment by nelsonic** [comment]
https://github.com/dwyl/start-here/commit/22e0595dbf057af9e35f9cb0d1b32ce1b59d8e39
![image](https://user-images.githubusercontent.com/194400/66544326-ba1d8d80-eb2f-11e9-8a9b-11a5c33bd36a.png)

This change is _innocuous_ but it demonstrates that _random_ people can `git push master --force` and _distroy_ all history of the repository ... 
![image](https://user-images.githubusercontent.com/194400/66544431-049f0a00-eb30-11e9-8ccc-696d2016a05b.png)

**Comment by nelsonic** [comment]
![image](https://user-images.githubusercontent.com/194400/77951562-2a78c080-72c2-11ea-8f07-6a72f07b013c.png)

![image](https://user-images.githubusercontent.com/194400/77952234-3618b700-72c3-11ea-9bb5-0890caf9c00e.png)

Obvs that token isn't valid. It's an 🥚 😉

**Comment by nelsonic** [comment]
PR: #7
